// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzzrllcoaqtszrskzxrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6enJsbGNvYXF0c3pyc2t6eHJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjExNzEsImV4cCI6MjA1OTY5NzE3MX0.FT6YfkwFAK6XMEOXKU62EhmscRRU4oTJykIoRGYdSAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);